Update validate-project-file.yml

diff --git a/.github/workflows/validate-project-file.yml b/.github/workflows/validate-project-file.yml
--- a/.github/workflows/validate-project-file.yml
+++ b/.github/workflows/validate-project-file.yml
@@ -9,12 +9,12 @@ on:
       - '.github/workflows/validate-project-file.yml'
       - 'test_validate_format.py'
       - 'validate_format.py'
-  pull_request:
-    paths:
-      - '_projects/*.md'
-      - '.github/workflows/validate-project-file.yml'
-      - 'test_validate_format.py'
-      - 'validate_format.py'
+  # pull_request:
+  #   paths:
+  #     - '_projects/*.md'
+  #     - '.github/workflows/validate-project-file.yml'
+  #     - 'test_validate_format.py'
+  #     - 'validate_format.py'
 
 jobs:
   validate:
@@ -64,11 +64,12 @@ jobs:
     - name: Validate all project files in main
       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
       run: |
-        find _projects -name '*.md' | while read file; do
-          output=$(python validate_format.py "$file" 2>&1) || {
-            echo "Validation failed for $file with message: $output"
-            exit 1
-          }
-          echo "$output"
-        done
+        pytest test_validate_format.py
+        # find _projects -name '*.md' | while read file; do
+        #   output=$(python validate_format.py "$file" 2>&1) || {
+        #     echo "Validation failed for $file with message: $output"
+        #     exit 1
+        #   }
+        #   echo "$output"
+        # done
       shell: bash
